name: 'healthcare_analytics'
version: '1.0.0'
config-version: 2

profile: 'healthcare_analytics'

model-paths:    ["models"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]
test-paths:     ["tests"]
target-path:    "target"
clean-targets:  ["target", "dbt_packages"]

models:
  healthcare_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts

seeds:
  healthcare_analytics:
    +schema: raw
    seed_doctors:
      +column_types: {doctor_id: varchar(5), years_experience: integer}
    seed_hospitals:
      +column_types: {hospital_id: varchar(5), bed_capacity: integer}
    seed_insurers:
      +column_types: {insurance_id: varchar(5)}

snapshots:
  healthcare_analytics:
    +target_schema: snapshots
